call_TISEANF_extended_upoembed <- function(data, bare_options, function_name)
{
	txt <- attr(data,"txt")
	out <- write_to_inputfile(ignore <- 1:10)
	if (out==1)
		stop("wrong input")
	tin<-input_filename()
	writeLines(txt, tin)
	tout=output_filename()
	options <- paste(tin," ",bare_options," -V0 -o",tout,"\n", sep="")
	toptions <- param_filename(0)
	.C("write_string_to_file2",as.character(options),as.integer(0),as.character(toptions),PACKAGE="RTisean")
	.Fortran(function_name,as.character(toptions),PACKAGE="RTisean")
	file.remove(toptions, tin)
	out <- read_TISEAN("")
	return(out)
}
